# Copyright © 2026 OpenCHAMI Contributors
# SPDX-License-Identifier: MIT

# NOTE: Must be configured either explicitly by the site administrator or
# implicitly via one of the OpenCHAMI deployment meta-configuration packages.

[Container]
# IDENTITY / SERVER
Environment=TOKENSMITH_ISSUER=
Environment=TOKENSMITH_PORT=8080
Environment=TOKENSMITH_CLUSTER_ID=
Environment=TOKENSMITH_OPENCHAMI_ID=

# UPSTREAM OIDC
Environment=TOKENSMITH_OIDC_PROVIDER=

# FILES / STATE
Environment=TOKENSMITH_CONFIG=/etc/tokensmith/config.json
Environment=TOKENSMITH_KEY_DIR=/tokensmith/data/keys
Environment=TOKENSMITH_RFC8693_BOOTSTRAP_STORE=/tokensmith/data/bootstrap
Environment=TOKENSMITH_RFC8693_REFRESH_STORE=/tokensmith/data/refresh

# EXAMPLE CONFIGURATION
# [Container]
# IDENTITY / SERVER
# Environment=TOKENSMITH_ISSUER=https://tokensmith.openchami.dev
# Environment=TOKENSMITH_PORT=8080
# Environment=TOKENSMITH_CLUSTER_ID=default-cluster
# Environment=TOKENSMITH_OPENCHAMI_ID=default-openchami
# 
# UPSTREAM OIDC
# Environment=TOKENSMITH_OIDC_PROVIDER=http://hydra:4444
# 
# FILES / STATE
# Environment=TOKENSMITH_CONFIG=/etc/tokensmith/config.json
# Environment=TOKENSMITH_KEY_DIR=/tokensmith/data/keys
# Environment=TOKENSMITH_RFC8693_BOOTSTRAP_STORE=/tokensmith/data/bootstrap
# Environment=TOKENSMITH_RFC8693_REFRESH_STORE=/tokensmith/data/refresh
