// Code generated by Fabrica v0.4.8-5-gc1ed6f1. DO NOT EDIT.
// Template: cmd/fabrica/generate.go:generateVersionedRegistrationCode
// Generated: 2026-06-30T20:26:32Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/openchami/tokensmith/apis/tokensmith.openchami.io/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.BootstrapTokenPolicy{}); err != nil {
		return fmt.Errorf("failed to register BootstrapTokenPolicy: %w", err)
	}
	if err := gen.RegisterResource(&v1.RefreshTokenFamily{}); err != nil {
		return fmt.Errorf("failed to register RefreshTokenFamily: %w", err)
	}
	if err := gen.RegisterResource(&v1.TokenHierarchy{}); err != nil {
		return fmt.Errorf("failed to register TokenHierarchy: %w", err)
	}

	return nil
}
