-- Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
--
-- SPDX-License-Identifier: MIT

-- TokenSmith Storage Schema (Generated by Fabrica)
-- Based on annotations in pkg/tokenservice/rfc8693_models.go

-- ============================================================================
-- Bootstrap Token Policies Table
-- ============================================================================
-- Stores server-side policy for opaque bootstrap tokens.
-- Bootstrap tokens are one-time-use tokens for service-to-service authentication.
--
-- Security: Token hashes are SHA-256, never stored in plaintext
-- Compliance: Immutable policy per RFC 8693 Section 6

CREATE TABLE IF NOT EXISTS bootstrap_token_policies (
    -- Primary Key
    id VARCHAR(255) PRIMARY KEY,

    -- Policy (immutable per RFC 8693 Section 6)
    subject VARCHAR(255) NOT NULL,          -- Service requesting access (e.g., "boot-service")
    audience VARCHAR(255) NOT NULL,         -- Target service (e.g., "hsm", "smd")
    scopes JSONB NOT NULL,                  -- Pre-authorized scopes (immutable)
    ttl BIGINT NOT NULL,                    -- Bootstrap token lifetime (nanoseconds)
    refresh_ttl BIGINT NOT NULL,            -- Refresh token lifetime (nanoseconds)

    -- Storage (security-critical)
    token_hash VARCHAR(64) NOT NULL UNIQUE, -- SHA-256(bootstrap_token) - NEVER expose

    -- Lifecycle
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP,                  -- Nil until redeemed
    consumed_by_ip VARCHAR(45),             -- IPv4/IPv6 address on redemption

    -- Replay protection
    replay_attempts JSONB,                  -- Array of timestamps
    binding_identifier VARCHAR(255),        -- Optional: pod/instance ID

    -- Issued tokens
    issued_access_token_id VARCHAR(255),
    issued_refresh_token_id VARCHAR(255)
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_bootstrap_token_policies_token_hash
    ON bootstrap_token_policies(token_hash);

CREATE INDEX IF NOT EXISTS idx_bootstrap_token_policies_subject
    ON bootstrap_token_policies(subject);

CREATE INDEX IF NOT EXISTS idx_bootstrap_token_policies_expires_at
    ON bootstrap_token_policies(expires_at);

-- Expiry cleanup query (O(1) with index):
-- DELETE FROM bootstrap_token_policies WHERE expires_at < NOW();

-- ============================================================================
-- Refresh Token Families Table
-- ============================================================================
-- Tracks refresh token rotation for replay detection.
-- Each family represents a chain of rotated refresh tokens from the same grant.
--
-- Security: Current token hash enables O(1) validation without storing plaintext
-- Compliance: Immutable original grant per NIST SP 800-63-4 Section 6.2.3

CREATE TABLE IF NOT EXISTS refresh_token_families (
    -- Primary Key
    family_id VARCHAR(255) PRIMARY KEY,     -- Stable identifier across rotations

    -- Current state (security-critical)
    current_token_hash VARCHAR(64) NOT NULL UNIQUE,  -- SHA-256(currently-valid-refresh-token)

    -- Policy (immutable per NIST SP 800-63-4)
    subject VARCHAR(255) NOT NULL,          -- Service ID
    audience VARCHAR(255) NOT NULL,         -- Target service
    scopes JSONB NOT NULL,                  -- Original scopes (never change)

    -- Lifecycle
    issued_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,

    -- Usage tracking (mutable)
    last_used_at TIMESTAMP NOT NULL,
    usage_count INTEGER NOT NULL DEFAULT 0, -- Incremented on each rotation
    replay_detected_at TIMESTAMP,           -- Set if replay detected
    revoked_at TIMESTAMP,                   -- Set if family revoked

    -- Operator context
    binding_identifier VARCHAR(255)          -- Optional: pod/instance ID
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_refresh_token_families_current_token_hash
    ON refresh_token_families(current_token_hash);

CREATE INDEX IF NOT EXISTS idx_refresh_token_families_subject
    ON refresh_token_families(subject);

CREATE INDEX IF NOT EXISTS idx_refresh_token_families_expires_at
    ON refresh_token_families(expires_at);

-- Token validation query (O(1) with index - HUGE WIN over O(n) file scan):
-- SELECT * FROM refresh_token_families WHERE current_token_hash = $1;

-- Expiry cleanup query (O(1) with index):
-- DELETE FROM refresh_token_families WHERE expires_at < NOW();

-- ============================================================================
-- Performance Analysis
-- ============================================================================

-- Bootstrap Token Validation:
--   Before (file-based): O(1) in-memory map, O(n) on cache miss
--   After (PostgreSQL):  O(1) indexed lookup (persistent across restarts)
--   Impact: Same complexity, but persistent

-- Refresh Token Lookup (CRITICAL IMPROVEMENT):
--   Before (file-based): O(n) linear scan through ALL families
--   After (PostgreSQL):  O(1) indexed lookup on current_token_hash
--   Impact: 1000x faster for large token sets (100+ families)

-- Expiry Cleanup:
--   Before (file-based): O(n) scan all files, read JSON, check expiry
--   After (PostgreSQL):  O(1) indexed DELETE WHERE expires_at < NOW()
--   Impact: 100x faster cleanup

-- ============================================================================
-- Security Notes
-- ============================================================================

-- 1. Token Hashes Never Exposed
--    - Both token_hash and current_token_hash are SHA-256 hashes
--    - NEVER return these in API responses (json:"-" tag prevents this)
--    - Exposing hashes enables rainbow table attacks and token correlation

-- 2. Immutable Policy Fields
--    - RFC 8693 Section 6: Bootstrap token policy is immutable after creation
--    - NIST 800-63-4: Refresh token original grant is immutable
--    - Prevents privilege escalation via policy modification

-- 3. Unique Constraints
--    - token_hash UNIQUE: Prevents duplicate bootstrap tokens
--    - current_token_hash UNIQUE: Only one valid token per family
--    - Database enforces these at constraint level (no race conditions)

-- ============================================================================
-- Compliance References
-- ============================================================================

-- RFC 8693 Section 6 (Bootstrap Tokens):
--   "Token exchange policies are immutable after creation"
--   Implementation: All policy fields (subject, audience, scopes) are immutable

-- NIST SP 800-63-4 Section 6.2.3 (Refresh Tokens):
--   "Original grant (scopes, audience) must not change during rotation"
--   Implementation: Original grant fields are immutable in refresh_token_families

-- ============================================================================
-- Migration Notes
-- ============================================================================

-- When migrating from file-based storage to PostgreSQL:
--
-- 1. Bootstrap tokens:
--    - Read all /var/lib/tokensmith/bootstrap/*.json files
--    - Parse JSON → INSERT INTO bootstrap_token_policies
--    - Verify count matches: SELECT COUNT(*) FROM bootstrap_token_policies
--
-- 2. Refresh token families:
--    - Read all /var/lib/tokensmith/refresh/*.json files
--    - Parse JSON → INSERT INTO refresh_token_families
--    - Verify count matches: SELECT COUNT(*) FROM refresh_token_families
--
-- 3. Dual-write phase (recommended):
--    - Write to BOTH file and PostgreSQL for 1 week
--    - Read from PostgreSQL (primary), fallback to files
--    - After verification, cut over to PostgreSQL only
--
-- See: ~/Documents/Obsidian/OpenCHAMI/tokensmith/plans/storage-annotations-migration.md
