// Code generated by Fabrica v0.4.8-5-gc1ed6f1 (commit: c1ed6f1). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains OpenAPI 3.0 specification generation for all resources.
// Generated from: pkg/codegen/templates/server/openapi.go.tmpl
//
// To modify OpenAPI spec:
//  1. Edit the template file: pkg/codegen/templates/server/openapi.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// OpenAPI endpoints:
//   - GET /openapi.json - Returns OpenAPI 3.0 spec
//   - GET /docs - Returns Swagger UI
//
// This file automatically generates OpenAPI schemas from Go types using
// kin-openapi's openapi3gen package. No docstring annotations required.
package main

import (
	"encoding/json"
	"net/http"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
	"github.com/openchami/tokensmith/apis/tokensmith.openchami.io/v1"
)

// ServeOpenAPISpec returns the OpenAPI 3.0 specification
func ServeOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	spec := GenerateOpenAPISpec()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(spec); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeSwaggerUI returns the Swagger UI HTML page
func ServeSwaggerUI(w http.ResponseWriter, r *http.Request) {
	html := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>tokensmith API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css">
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin:0; padding:0; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle({
                url: "/openapi.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`
	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(html))
}

// GenerateOpenAPISpec generates the complete OpenAPI 3.0 specification
func GenerateOpenAPISpec() *openapi3.T {
	spec := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:       "tokensmith API",
			Description: "Fabrica-generated REST API with Kubernetes-style resource management",
			Version:     "1.0.0",
			Contact: &openapi3.Contact{
				Name: "Fabrica Project",
				URL:  "https://github.com/openchami/fabrica",
			},
		},
		Servers: openapi3.Servers{
			{
				URL:         "http://localhost:8080",
				Description: "Development server",
			},
		},
		Paths: openapi3.NewPaths(),
		Components: &openapi3.Components{
			Schemas: make(openapi3.Schemas),
		},
	}

	// Register all resource paths
	registerBootstrapTokenPolicyPaths(spec)
	registerRefreshTokenFamilyPaths(spec)
	registerTokenHierarchyPaths(spec)

	// Register /health endpoint
	healthOp := openapi3.NewOperation()
	healthOp.OperationID = "health"
	healthOp.Summary = "Service health"
	healthOp.Description = "Returns service health information"
	healthOp.Tags = []string{"Service"}
	healthResponseSchema := openapi3.NewObjectSchema().
		WithProperty("status", openapi3.NewStringSchema()).
		WithProperty("service", openapi3.NewStringSchema()).
		WithProperty("version", openapi3.NewStringSchema()).
		WithProperty("time", openapi3.NewStringSchema()).
		WithRequired([]string{"status"})
	healthExample := map[string]interface{}{
		"status":  "ok",
		"service": "tokensmith",
		"version": "1.0.0",
		"time":    "2026-01-01T00:00:00Z",
	}
	healthResponseSchema.Example = healthExample
	healthOp.Responses = openapi3.NewResponses()
	healthOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Healthy").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: healthResponseSchema},
					Example: healthExample,
				},
			}),
	})
	spec.Paths.Set("/health", &openapi3.PathItem{Get: healthOp})

	// Register /openapi.json endpoint (self-referential spec endpoint)
	openAPIJSONExample := map[string]interface{}{
		"openapi": "3.0.0",
		"info": map[string]interface{}{
			"title":   "tokensmith API",
			"version": "1.0.0",
		},
	}
	openAPIJsonOp := openapi3.NewOperation()
	openAPIJsonOp.OperationID = "getOpenAPISpec"
	openAPIJsonOp.Summary = "Get OpenAPI specification"
	openAPIJsonOp.Description = "Returns the complete OpenAPI 3.0 specification for this API"
	openAPIJsonOp.Tags = []string{"Service"}
	openAPIJsonOp.Responses = openapi3.NewResponses()
	openAPIJsonOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("OpenAPI specification").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()},
					Example: openAPIJSONExample,
				},
			}),
	})
	spec.Paths.Set("/openapi.json", &openapi3.PathItem{Get: openAPIJsonOp})

	// Register /docs endpoint (Swagger UI)
	docsOp := openapi3.NewOperation()
	docsOp.OperationID = "getSwaggerUI"
	docsOp.Summary = "API documentation UI"
	docsOp.Description = "Returns an interactive Swagger UI for exploring the API"
	docsOp.Tags = []string{"Service"}
	docsOp.Responses = openapi3.NewResponses()
	docsOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Swagger UI HTML page").
			WithContent(map[string]*openapi3.MediaType{
				"text/html": {
					Schema: &openapi3.SchemaRef{Value: openapi3.NewStringSchema()},
				},
			}),
	})
	spec.Paths.Set("/docs", &openapi3.PathItem{Get: docsOp})

	// Register custom (non-Fabrica-generated) paths.
	// Defined in openapi_extensions.go – safe to edit, never overwritten.
	registerCustomOpenAPIPaths(spec)

	return spec
}

// registerBootstrapTokenPolicyPaths registers OpenAPI paths for BootstrapTokenPolicy resources
func registerBootstrapTokenPolicyPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.BootstrapTokenPolicy{}, spec.Components.Schemas)
	spec.Components.Schemas["BootstrapTokenPolicy"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateBootstrapTokenPolicyRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateBootstrapTokenPolicyRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateBootstrapTokenPolicyRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateBootstrapTokenPolicyRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.BootstrapTokenPolicyStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["BootstrapTokenPolicyStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List BootstrapTokenPolicys operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listBootstrapTokenPolicys"
	listOp.Summary = "List all BootstrapTokenPolicy resources"
	listOp.Description = "Returns a list of all BootstrapTokenPolicy resources in the inventory"
	listOp.Tags = []string{"BootstrapTokenPolicy"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/BootstrapTokenPolicy"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create BootstrapTokenPolicy operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createBootstrapTokenPolicy"
	createOp.Summary = "Create a new BootstrapTokenPolicy resource"
	createOp.Description = "Creates a new BootstrapTokenPolicy resource with the provided specification"
	createOp.Tags = []string{"BootstrapTokenPolicy"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateBootstrapTokenPolicyRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BootstrapTokenPolicy",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get BootstrapTokenPolicy operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getBootstrapTokenPolicy"
	getOp.Summary = "Get a specific BootstrapTokenPolicy resource"
	getOp.Description = "Returns details of a specific BootstrapTokenPolicy resource by UID"
	getOp.Tags = []string{"BootstrapTokenPolicy"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BootstrapTokenPolicy",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update BootstrapTokenPolicy operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateBootstrapTokenPolicy"
	updateOp.Summary = "Update a BootstrapTokenPolicy resource"
	updateOp.Description = "Updates an existing BootstrapTokenPolicy resource with new values"
	updateOp.Tags = []string{"BootstrapTokenPolicy"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateBootstrapTokenPolicyRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BootstrapTokenPolicy",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch BootstrapTokenPolicy operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchBootstrapTokenPolicy"
	patchOp.Summary = "Patch a BootstrapTokenPolicy resource"
	patchOp.Description = "Partially updates an existing BootstrapTokenPolicy resource using patch semantics"
	patchOp.Tags = []string{"BootstrapTokenPolicy"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/BootstrapTokenPolicy",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update BootstrapTokenPolicy status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateBootstrapTokenPolicyStatus"
	updateStatusOp.Summary = "Update BootstrapTokenPolicy status"
	updateStatusOp.Description = "Updates only the status subresource for an existing BootstrapTokenPolicy"
	updateStatusOp.Tags = []string{"BootstrapTokenPolicy"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BootstrapTokenPolicyStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BootstrapTokenPolicy"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch BootstrapTokenPolicy status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchBootstrapTokenPolicyStatus"
	patchStatusOp.Summary = "Patch BootstrapTokenPolicy status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing BootstrapTokenPolicy"
	patchStatusOp.Tags = []string{"BootstrapTokenPolicy"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/BootstrapTokenPolicy"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete BootstrapTokenPolicy operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteBootstrapTokenPolicy"
	deleteOp.Summary = "Delete a BootstrapTokenPolicy resource"
	deleteOp.Description = "Removes a BootstrapTokenPolicy resource from the inventory"
	deleteOp.Tags = []string{"BootstrapTokenPolicy"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the BootstrapTokenPolicy resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/bootstraptokenpolicys", collectionPath)
	spec.Paths.Set("/bootstraptokenpolicys/{uid}", itemPath)
	spec.Paths.Set("/bootstraptokenpolicys/{uid}/status", statusPath)
}

// registerRefreshTokenFamilyPaths registers OpenAPI paths for RefreshTokenFamily resources
func registerRefreshTokenFamilyPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.RefreshTokenFamily{}, spec.Components.Schemas)
	spec.Components.Schemas["RefreshTokenFamily"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateRefreshTokenFamilyRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateRefreshTokenFamilyRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateRefreshTokenFamilyRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateRefreshTokenFamilyRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.RefreshTokenFamilyStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["RefreshTokenFamilyStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List RefreshTokenFamilys operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listRefreshTokenFamilys"
	listOp.Summary = "List all RefreshTokenFamily resources"
	listOp.Description = "Returns a list of all RefreshTokenFamily resources in the inventory"
	listOp.Tags = []string{"RefreshTokenFamily"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/RefreshTokenFamily"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create RefreshTokenFamily operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createRefreshTokenFamily"
	createOp.Summary = "Create a new RefreshTokenFamily resource"
	createOp.Description = "Creates a new RefreshTokenFamily resource with the provided specification"
	createOp.Tags = []string{"RefreshTokenFamily"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateRefreshTokenFamilyRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/RefreshTokenFamily",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get RefreshTokenFamily operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getRefreshTokenFamily"
	getOp.Summary = "Get a specific RefreshTokenFamily resource"
	getOp.Description = "Returns details of a specific RefreshTokenFamily resource by UID"
	getOp.Tags = []string{"RefreshTokenFamily"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/RefreshTokenFamily",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update RefreshTokenFamily operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateRefreshTokenFamily"
	updateOp.Summary = "Update a RefreshTokenFamily resource"
	updateOp.Description = "Updates an existing RefreshTokenFamily resource with new values"
	updateOp.Tags = []string{"RefreshTokenFamily"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateRefreshTokenFamilyRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/RefreshTokenFamily",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch RefreshTokenFamily operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchRefreshTokenFamily"
	patchOp.Summary = "Patch a RefreshTokenFamily resource"
	patchOp.Description = "Partially updates an existing RefreshTokenFamily resource using patch semantics"
	patchOp.Tags = []string{"RefreshTokenFamily"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/RefreshTokenFamily",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update RefreshTokenFamily status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateRefreshTokenFamilyStatus"
	updateStatusOp.Summary = "Update RefreshTokenFamily status"
	updateStatusOp.Description = "Updates only the status subresource for an existing RefreshTokenFamily"
	updateStatusOp.Tags = []string{"RefreshTokenFamily"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/RefreshTokenFamilyStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/RefreshTokenFamily"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch RefreshTokenFamily status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchRefreshTokenFamilyStatus"
	patchStatusOp.Summary = "Patch RefreshTokenFamily status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing RefreshTokenFamily"
	patchStatusOp.Tags = []string{"RefreshTokenFamily"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/RefreshTokenFamily"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete RefreshTokenFamily operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteRefreshTokenFamily"
	deleteOp.Summary = "Delete a RefreshTokenFamily resource"
	deleteOp.Description = "Removes a RefreshTokenFamily resource from the inventory"
	deleteOp.Tags = []string{"RefreshTokenFamily"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the RefreshTokenFamily resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/refreshtokenfamilys", collectionPath)
	spec.Paths.Set("/refreshtokenfamilys/{uid}", itemPath)
	spec.Paths.Set("/refreshtokenfamilys/{uid}/status", statusPath)
}

// registerTokenHierarchyPaths registers OpenAPI paths for TokenHierarchy resources
func registerTokenHierarchyPaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.TokenHierarchy{}, spec.Components.Schemas)
	spec.Components.Schemas["TokenHierarchy"] = resourceSchema

	createReqSchema, _ := openapi3gen.NewSchemaRefForValue(&CreateTokenHierarchyRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["CreateTokenHierarchyRequest"] = createReqSchema

	updateReqSchema, _ := openapi3gen.NewSchemaRefForValue(&UpdateTokenHierarchyRequest{}, spec.Components.Schemas)
	spec.Components.Schemas["UpdateTokenHierarchyRequest"] = updateReqSchema

	statusSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.TokenHierarchyStatus{}, spec.Components.Schemas)
	spec.Components.Schemas["TokenHierarchyStatus"] = statusSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}

	// DELETE response schema
	if _, exists := spec.Components.Schemas["DeleteResponse"]; !exists {
		deleteSchema, _ := openapi3gen.NewSchemaRefForValue(&DeleteResponse{}, spec.Components.Schemas)
		spec.Components.Schemas["DeleteResponse"] = deleteSchema
	}

	// List TokenHierarchys operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listTokenHierarchys"
	listOp.Summary = "List all TokenHierarchy resources"
	listOp.Description = "Returns a list of all TokenHierarchy resources in the inventory"
	listOp.Tags = []string{"TokenHierarchy"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/TokenHierarchy"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create TokenHierarchy operation
	createOp := openapi3.NewOperation()
	createOp.OperationID = "createTokenHierarchy"
	createOp.Summary = "Create a new TokenHierarchy resource"
	createOp.Description = "Creates a new TokenHierarchy resource with the provided specification"
	createOp.Tags = []string{"TokenHierarchy"}
	createOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/CreateTokenHierarchyRequest",
			}),
	}
	createOp.Responses = openapi3.NewResponses()
	createOp.Responses.Set("201", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource created successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/TokenHierarchy",
			}),
	})
	createOp.Responses.Set("400", errorResponse())
	createOp.Responses.Set("500", errorResponse())

	// Get TokenHierarchy operation
	getOp := openapi3.NewOperation()
	getOp.OperationID = "getTokenHierarchy"
	getOp.Summary = "Get a specific TokenHierarchy resource"
	getOp.Description = "Returns details of a specific TokenHierarchy resource by UID"
	getOp.Tags = []string{"TokenHierarchy"}
	getOp.Responses = openapi3.NewResponses()
	getOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/TokenHierarchy",
			}),
	})
	getOp.Responses.Set("404", errorResponse())
	getOp.Responses.Set("500", errorResponse())

	// Update TokenHierarchy operation
	updateOp := openapi3.NewOperation()
	updateOp.OperationID = "updateTokenHierarchy"
	updateOp.Summary = "Update a TokenHierarchy resource"
	updateOp.Description = "Updates an existing TokenHierarchy resource with new values"
	updateOp.Tags = []string{"TokenHierarchy"}
	updateOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/UpdateTokenHierarchyRequest",
			}),
	}
	updateOp.Responses = openapi3.NewResponses()
	updateOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/TokenHierarchy",
			}),
	})
	updateOp.Responses.Set("400", errorResponse())
	updateOp.Responses.Set("404", errorResponse())
	updateOp.Responses.Set("500", errorResponse())

	// Patch TokenHierarchy operation
	patchOp := openapi3.NewOperation()
	patchOp.OperationID = "patchTokenHierarchy"
	patchOp.Summary = "Patch a TokenHierarchy resource"
	patchOp.Description = "Partially updates an existing TokenHierarchy resource using patch semantics"
	patchOp.Tags = []string{"TokenHierarchy"}
	patchOp.RequestBody = patchRequestBody()
	patchOp.Responses = openapi3.NewResponses()
	patchOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/TokenHierarchy",
			}),
	})
	patchOp.Responses.Set("400", errorResponse())
	patchOp.Responses.Set("404", errorResponse())
	patchOp.Responses.Set("422", errorResponse())
	patchOp.Responses.Set("500", errorResponse())

	// Update TokenHierarchy status operation
	updateStatusOp := openapi3.NewOperation()
	updateStatusOp.OperationID = "updateTokenHierarchyStatus"
	updateStatusOp.Summary = "Update TokenHierarchy status"
	updateStatusOp.Description = "Updates only the status subresource for an existing TokenHierarchy"
	updateStatusOp.Tags = []string{"TokenHierarchy"}
	updateStatusOp.RequestBody = &openapi3.RequestBodyRef{
		Value: openapi3.NewRequestBody().
			WithRequired(true).
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/TokenHierarchyStatus"}),
	}
	updateStatusOp.Responses = openapi3.NewResponses()
	updateStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status updated successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/TokenHierarchy"}),
	})
	updateStatusOp.Responses.Set("400", errorResponse())
	updateStatusOp.Responses.Set("404", errorResponse())
	updateStatusOp.Responses.Set("500", errorResponse())

	// Patch TokenHierarchy status operation
	patchStatusOp := openapi3.NewOperation()
	patchStatusOp.OperationID = "patchTokenHierarchyStatus"
	patchStatusOp.Summary = "Patch TokenHierarchy status"
	patchStatusOp.Description = "Partially updates only the status subresource for an existing TokenHierarchy"
	patchStatusOp.Tags = []string{"TokenHierarchy"}
	patchStatusOp.RequestBody = patchRequestBody()
	patchStatusOp.Responses = openapi3.NewResponses()
	patchStatusOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Status patched successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{Ref: "#/components/schemas/TokenHierarchy"}),
	})
	patchStatusOp.Responses.Set("400", errorResponse())
	patchStatusOp.Responses.Set("404", errorResponse())
	patchStatusOp.Responses.Set("422", errorResponse())
	patchStatusOp.Responses.Set("500", errorResponse())

	// Delete TokenHierarchy operation
	deleteOp := openapi3.NewOperation()
	deleteOp.OperationID = "deleteTokenHierarchy"
	deleteOp.Summary = "Delete a TokenHierarchy resource"
	deleteOp.Description = "Removes a TokenHierarchy resource from the inventory"
	deleteOp.Tags = []string{"TokenHierarchy"}
	deleteOp.Responses = openapi3.NewResponses()
	deleteOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Resource deleted successfully").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/DeleteResponse",
			}),
	})
	deleteOp.Responses.Set("400", errorResponse())
	deleteOp.Responses.Set("404", errorResponse())
	deleteOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get:  listOp,
		Post: createOp,
	}

	uidParam := openapi3.NewPathParameter("uid").
		WithDescription("Unique identifier of the TokenHierarchy resource").
		WithRequired(true).
		WithSchema(openapi3.NewStringSchema())

	itemPath := &openapi3.PathItem{
		Get:    getOp,
		Put:    updateOp,
		Patch:  patchOp,
		Delete: deleteOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	statusPath := &openapi3.PathItem{
		Put:   updateStatusOp,
		Patch: patchStatusOp,
		Parameters: []*openapi3.ParameterRef{
			{Value: uidParam},
		},
	}

	// Add paths to spec
	spec.Paths.Set("/tokenhierarchys", collectionPath)
	spec.Paths.Set("/tokenhierarchys/{uid}", itemPath)
	spec.Paths.Set("/tokenhierarchys/{uid}/status", statusPath)
}

func patchRequestBody() *openapi3.RequestBodyRef {
	patchSchema := &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()}
	return &openapi3.RequestBodyRef{
		Value: &openapi3.RequestBody{
			Required: true,
			Content: openapi3.Content{
				"application/merge-patch+json": &openapi3.MediaType{Schema: patchSchema},
				"application/json-patch+json":  &openapi3.MediaType{Schema: patchSchema},
				"application/shorthand-patch":  &openapi3.MediaType{Schema: patchSchema},
				"application/json":             &openapi3.MediaType{Schema: patchSchema},
			},
		},
	}
}

// Helper function for error responses
func errorResponse() *openapi3.ResponseRef {
	return &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Error response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ErrorResponse",
			}),
	}
}
