// Code generated by Fabrica v0.4.5-dirty (commit: 0a2be92). DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-06-30T16:07:28Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for RefreshTokenFamily resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /refreshtokenfamilys (list all refreshtokenfamilys)
//   - GET /refreshtokenfamilys/{uid} (get specific RefreshTokenFamily)
//   - POST /refreshtokenfamilys (create new RefreshTokenFamily)
//   - PUT /refreshtokenfamilys/{uid} (update RefreshTokenFamily spec)
//   - PATCH /refreshtokenfamilys/{uid} (patch RefreshTokenFamily spec)
//   - DELETE /refreshtokenfamilys/{uid} (delete RefreshTokenFamily)
//   - PUT /refreshtokenfamilys/{uid}/status (update RefreshTokenFamily status)
//   - PATCH /refreshtokenfamilys/{uid}/status (patch RefreshTokenFamily status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadRefreshTokenFamily*/SaveRefreshTokenFamily*/DeleteRefreshTokenFamily*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadRefreshTokenFamilyWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/openchami/tokensmith/apis/tokensmith.openchami.io/v1"

	"github.com/openchami/tokensmith/internal/storage"
)

// GetRefreshTokenFamilys returns all RefreshTokenFamily resources
func GetRefreshTokenFamilys(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	refreshtokenfamilys, err := storage.LoadAllRefreshTokenFamilys(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load refreshtokenfamilys: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, refreshtokenfamilys)
}

// GetRefreshTokenFamily returns a specific RefreshTokenFamily resource by UID
func GetRefreshTokenFamily(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("RefreshTokenFamily UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadRefreshTokenFamily() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	refreshTokenFamily, err := storage.LoadRefreshTokenFamily(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("RefreshTokenFamily not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, refreshTokenFamily)
}

// CreateRefreshTokenFamily creates a new RefreshTokenFamily resource
func CreateRefreshTokenFamily(w http.ResponseWriter, r *http.Request) {
	var req CreateRefreshTokenFamilyRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("RefreshTokenFamily")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	refreshTokenFamily := &v1.RefreshTokenFamily{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "RefreshTokenFamily",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	refreshTokenFamily.Metadata = req.Metadata
	refreshTokenFamily.Metadata.UID = uid
	now := time.Now()
	refreshTokenFamily.Metadata.CreatedAt = now
	refreshTokenFamily.Metadata.UpdatedAt = now

	// Set labels and annotations
	if refreshTokenFamily.Metadata.Labels == nil {
		refreshTokenFamily.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		refreshTokenFamily.Metadata.Labels[k] = v
	}
	if refreshTokenFamily.Metadata.Annotations == nil {
		refreshTokenFamily.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		refreshTokenFamily.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), refreshTokenFamily); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveRefreshTokenFamily(r.Context(), refreshTokenFamily); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save RefreshTokenFamily: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "RefreshTokenFamily", refreshTokenFamily.Metadata.UID, refreshTokenFamily.Metadata.Name, refreshTokenFamily); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for RefreshTokenFamily %s: %v\n", refreshTokenFamily.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, refreshTokenFamily)
}

// UpdateRefreshTokenFamily updates the spec of an existing RefreshTokenFamily resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //refreshtokenfamilys/{uid}/status to update status.
func UpdateRefreshTokenFamily(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("RefreshTokenFamily UID is required"))
		return
	}

	refreshTokenFamily, err := storage.LoadRefreshTokenFamily(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("RefreshTokenFamily not found: %w", err))
		return
	}

	var req UpdateRefreshTokenFamilyRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		refreshTokenFamily.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	refreshTokenFamily.Spec = req.AsSpec()

	// Update labels and annotations
	if refreshTokenFamily.Metadata.Labels == nil {
		refreshTokenFamily.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		refreshTokenFamily.Metadata.Labels[k] = v
	}
	if refreshTokenFamily.Metadata.Annotations == nil {
		refreshTokenFamily.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		refreshTokenFamily.Metadata.Annotations[k] = v
	}

	// Update timestamp
	refreshTokenFamily.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), refreshTokenFamily); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveRefreshTokenFamily(r.Context(), refreshTokenFamily); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save RefreshTokenFamily: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": refreshTokenFamily.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "RefreshTokenFamily", refreshTokenFamily.Metadata.UID, refreshTokenFamily.Metadata.Name, refreshTokenFamily, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for RefreshTokenFamily %s: %v\n", refreshTokenFamily.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, refreshTokenFamily)
}

// PatchRefreshTokenFamily patches an existing RefreshTokenFamily resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchRefreshTokenFamily(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("RefreshTokenFamily UID is required"))
		return
	}

	refreshTokenFamily, err := storage.LoadRefreshTokenFamily(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("RefreshTokenFamily not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(refreshTokenFamily.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &refreshTokenFamily.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	refreshTokenFamily.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), refreshTokenFamily); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Save the patched resource
	if err := storage.SaveRefreshTokenFamily(r.Context(), refreshTokenFamily); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched RefreshTokenFamily: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": refreshTokenFamily.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "RefreshTokenFamily", refreshTokenFamily.Metadata.UID, refreshTokenFamily.Metadata.Name, refreshTokenFamily, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for RefreshTokenFamily %s: %v\n", refreshTokenFamily.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, refreshTokenFamily)
}

// UpdateRefreshTokenFamilyStatus updates only the status of a RefreshTokenFamily resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateRefreshTokenFamilyStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("RefreshTokenFamily UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadRefreshTokenFamily(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("RefreshTokenFamily not found: %w", err))
		return
	}

	var statusUpdate v1.RefreshTokenFamilyStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveRefreshTokenFamily(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save RefreshTokenFamily status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "RefreshTokenFamily", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for RefreshTokenFamily %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchRefreshTokenFamilyStatus patches only the status of a RefreshTokenFamily resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchRefreshTokenFamilyStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("RefreshTokenFamily UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadRefreshTokenFamily(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("RefreshTokenFamily not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveRefreshTokenFamily(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched RefreshTokenFamily status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "RefreshTokenFamily", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for RefreshTokenFamily %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteRefreshTokenFamily deletes a RefreshTokenFamily resource
func DeleteRefreshTokenFamily(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("RefreshTokenFamily UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	refreshTokenFamily, err := storage.LoadRefreshTokenFamily(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("RefreshTokenFamily not found: %w", err))
		return
	}

	if err := storage.DeleteRefreshTokenFamily(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete RefreshTokenFamily: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "RefreshTokenFamily", refreshTokenFamily.Metadata.UID, refreshTokenFamily.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for RefreshTokenFamily %s: %v\n", refreshTokenFamily.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "RefreshTokenFamily deleted successfully",
		UID:     uid,
	})
}
