// Code generated by Fabrica v0.4.8-5-gc1ed6f1 (commit: c1ed6f1). DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-06-30T20:26:34Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for TokenHierarchy resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /tokenhierarchys (list all tokenhierarchys)
//   - GET /tokenhierarchys/{uid} (get specific TokenHierarchy)
//   - POST /tokenhierarchys (create new TokenHierarchy)
//   - PUT /tokenhierarchys/{uid} (update TokenHierarchy spec)
//   - PATCH /tokenhierarchys/{uid} (patch TokenHierarchy spec)
//   - DELETE /tokenhierarchys/{uid} (delete TokenHierarchy)
//   - PUT /tokenhierarchys/{uid}/status (update TokenHierarchy status)
//   - PATCH /tokenhierarchys/{uid}/status (patch TokenHierarchy status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadTokenHierarchy*/SaveTokenHierarchy*/DeleteTokenHierarchy*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadTokenHierarchyWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/openchami/tokensmith/apis/tokensmith.openchami.io/v1"

	"github.com/openchami/tokensmith/internal/storage"
)

// GetTokenHierarchys returns all TokenHierarchy resources
func GetTokenHierarchys(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	tokenhierarchys, err := storage.LoadAllTokenHierarchys(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load tokenhierarchys: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, tokenhierarchys)
}

// GetTokenHierarchy returns a specific TokenHierarchy resource by UID
func GetTokenHierarchy(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("TokenHierarchy UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadTokenHierarchy() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	tokenHierarchy, err := storage.LoadTokenHierarchy(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("TokenHierarchy not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, tokenHierarchy)
}

// CreateTokenHierarchy creates a new TokenHierarchy resource
func CreateTokenHierarchy(w http.ResponseWriter, r *http.Request) {
	var req CreateTokenHierarchyRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("TokenHierarchy")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	tokenHierarchy := &v1.TokenHierarchy{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "TokenHierarchy",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	tokenHierarchy.Metadata = req.Metadata
	tokenHierarchy.Metadata.UID = uid
	now := time.Now()
	tokenHierarchy.Metadata.CreatedAt = now
	tokenHierarchy.Metadata.UpdatedAt = now

	// Set labels and annotations
	if tokenHierarchy.Metadata.Labels == nil {
		tokenHierarchy.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		tokenHierarchy.Metadata.Labels[k] = v
	}
	if tokenHierarchy.Metadata.Annotations == nil {
		tokenHierarchy.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		tokenHierarchy.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), tokenHierarchy); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveTokenHierarchy(r.Context(), tokenHierarchy); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save TokenHierarchy: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "TokenHierarchy", tokenHierarchy.Metadata.UID, tokenHierarchy.Metadata.Name, tokenHierarchy); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for TokenHierarchy %s: %v\n", tokenHierarchy.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, tokenHierarchy)
}

// UpdateTokenHierarchy updates the spec of an existing TokenHierarchy resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //tokenhierarchys/{uid}/status to update status.
func UpdateTokenHierarchy(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("TokenHierarchy UID is required"))
		return
	}

	tokenHierarchy, err := storage.LoadTokenHierarchy(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("TokenHierarchy not found: %w", err))
		return
	}

	var req UpdateTokenHierarchyRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		tokenHierarchy.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	tokenHierarchy.Spec = req.AsSpec()

	// Update labels and annotations
	if tokenHierarchy.Metadata.Labels == nil {
		tokenHierarchy.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		tokenHierarchy.Metadata.Labels[k] = v
	}
	if tokenHierarchy.Metadata.Annotations == nil {
		tokenHierarchy.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		tokenHierarchy.Metadata.Annotations[k] = v
	}

	// Update timestamp
	tokenHierarchy.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), tokenHierarchy); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveTokenHierarchy(r.Context(), tokenHierarchy); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save TokenHierarchy: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": tokenHierarchy.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "TokenHierarchy", tokenHierarchy.Metadata.UID, tokenHierarchy.Metadata.Name, tokenHierarchy, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for TokenHierarchy %s: %v\n", tokenHierarchy.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, tokenHierarchy)
}

// PatchTokenHierarchy patches an existing TokenHierarchy resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchTokenHierarchy(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("TokenHierarchy UID is required"))
		return
	}

	tokenHierarchy, err := storage.LoadTokenHierarchy(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("TokenHierarchy not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(tokenHierarchy.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &tokenHierarchy.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	tokenHierarchy.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), tokenHierarchy); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Save the patched resource
	if err := storage.SaveTokenHierarchy(r.Context(), tokenHierarchy); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched TokenHierarchy: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": tokenHierarchy.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "TokenHierarchy", tokenHierarchy.Metadata.UID, tokenHierarchy.Metadata.Name, tokenHierarchy, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for TokenHierarchy %s: %v\n", tokenHierarchy.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, tokenHierarchy)
}

// UpdateTokenHierarchyStatus updates only the status of a TokenHierarchy resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateTokenHierarchyStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("TokenHierarchy UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadTokenHierarchy(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("TokenHierarchy not found: %w", err))
		return
	}

	var statusUpdate v1.TokenHierarchyStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveTokenHierarchy(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save TokenHierarchy status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "TokenHierarchy", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for TokenHierarchy %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchTokenHierarchyStatus patches only the status of a TokenHierarchy resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchTokenHierarchyStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("TokenHierarchy UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadTokenHierarchy(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("TokenHierarchy not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), res); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	if err := storage.SaveTokenHierarchy(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched TokenHierarchy status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "TokenHierarchy", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for TokenHierarchy %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteTokenHierarchy deletes a TokenHierarchy resource
func DeleteTokenHierarchy(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("TokenHierarchy UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	tokenHierarchy, err := storage.LoadTokenHierarchy(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("TokenHierarchy not found: %w", err))
		return
	}

	if err := storage.DeleteTokenHierarchy(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete TokenHierarchy: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "TokenHierarchy", tokenHierarchy.Metadata.UID, tokenHierarchy.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for TokenHierarchy %s: %v\n", tokenHierarchy.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "TokenHierarchy deleted successfully",
		UID:     uid,
	})
}
