// Code generated by Fabrica v0.4.8-5-gc1ed6f1 (commit: c1ed6f1). DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Cobra-based CLI for the tokensmith API.
// Generated from: pkg/codegen/templates/client-cmd.go.tmpl
//
// To modify the CLI:
//  1. Edit the template file: pkg/codegen/templates/client-cmd.go.tmpl
//  2. Run 'make generate-client-cmd' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated commands for each resource:
//   - client health
//   - client bootstraptokenpolicy [list|get|create|update|patch|delete]
//   - client refreshtokenfamily [list|get|create|update|patch|delete]
//   - client tokenhierarchy [list|get|create|update|patch|delete]
//
// Global flags (available for all commands):
//
//	--server       Server URL (env: TOKENSMITH_SERVER)
//	--timeout      Request timeout (env: TOKENSMITH_TIMEOUT)
//	--output, -o   Output format: table, json, yaml (env: TOKENSMITH_OUTPUT)
//	--version, -v  API version to request: v1, v2beta1, etc. (env: TOKENSMITH_VERSION)
//	--token        JWT bearer token (env: TOKENSMITH_TOKEN)
//	--config       Config file path (default: ~/.tokensmith-cli.yaml)
//
// Configuration sources (in order of precedence):
//  1. Command-line flags
//  2. Environment variables (TOKENSMITH_*)
//  3. Config file (~/.tokensmith-cli.yaml)
//  4. Default values
//
// Usage examples:
//
//	# List all bootstraptokenpolicys (default version)
//	client bootstraptokenpolicy list
//
//	# List bootstraptokenpolicys with specific version
//	client bootstraptokenpolicy list --version v2beta1
//
//	# Get BootstrapTokenPolicy as v1
//	client bootstraptokenpolicy get <uid> --version v1
//
//	# Create from JSON file with version
//	cat bootstraptokenpolicy.json | client bootstraptokenpolicy create --version v2beta1
//
//	# Create from inline JSON
//	client bootstraptokenpolicy create --spec '{"name":"bootstraptokenpolicy-01","description":"Example BootstrapTokenPolicy"}'
//
//	# Use environment variables
//	export TOKENSMITH_SERVER=https://tokensmith.example.com
//	export TOKENSMITH_VERSION=v2beta1
//	client bootstraptokenpolicy list
//
// To add custom commands:
//  1. Add command definition in template after resource commands
//  2. Register it in init() function
//
// To change output formatting:
//  1. Modify printOutput function to add new formats
//  2. Update output flag validation
//
// To add authentication:
//  1. Add auth flags (--token, --username, etc.)
//  2. Modify getClient to configure auth in http.Client
//  3. Add auth headers in client package
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/openchami/tokensmith/pkg/client"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	cfgFile     string
	serverURL   string
	timeout     time.Duration
	output      string
	apiVersion  string
	bearerToken string
	logLevel    client.LogLevel
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   filepath.Base(os.Args[0]),
	Short: "tokensmith CLI",
	Long:  `A command-line interface for managing tokensmith resources.`,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.tokensmith-cli.yaml)")
	rootCmd.PersistentFlags().StringVar(&serverURL, "server", "http://localhost:8080", "tokensmith server URL")
	rootCmd.PersistentFlags().DurationVar(&timeout, "timeout", 30*time.Second, "request timeout")
	rootCmd.PersistentFlags().StringVarP(&output, "output", "o", "table", "output format: table, json, yaml")
	rootCmd.PersistentFlags().StringVarP(&apiVersion, "version", "v", "", "API version to request (e.g., v1, v2beta1)")
	rootCmd.PersistentFlags().StringVar(&bearerToken, "token", "", "JWT bearer token")
	rootCmd.PersistentFlags().VarP(&logLevel, "log-level", "l", "set verbosity of logs (e.g., info, warning, debug)")

	// Register shell completion functions
	rootCmd.RegisterFlagCompletionFunc("log-level", client.CompletionLogLevel)

	// Bind flags to viper
	viper.BindPFlag("server", rootCmd.PersistentFlags().Lookup("server"))
	viper.BindPFlag("timeout", rootCmd.PersistentFlags().Lookup("timeout"))
	viper.BindPFlag("output", rootCmd.PersistentFlags().Lookup("output"))
	viper.BindPFlag("version", rootCmd.PersistentFlags().Lookup("version"))
	viper.BindPFlag("token", rootCmd.PersistentFlags().Lookup("token"))
	viper.BindPFlag("log-level", rootCmd.PersistentFlags().Lookup("log-level"))

	// Environment variable support
	viper.SetEnvPrefix("TOKENSMITH")
	viper.AutomaticEnv()

	// Add resource commands
	rootCmd.AddCommand(healthCmd)
	rootCmd.AddCommand(bootstraptokenpolicyCmd)
	rootCmd.AddCommand(refreshtokenfamilyCmd)
	rootCmd.AddCommand(tokenhierarchyCmd)

}

func initConfig() {
	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %v\n", err)
			return
		}

		viper.AddConfigPath(home)
		viper.SetConfigType("yaml")
		viper.SetConfigName(".tokensmith-cli")
	}

	if err := viper.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
	}
}

func getClient() (*client.Client, error) {
	serverURL := viper.GetString("server")
	// Error will cause default logger, which is handled by NewClient()
	logger, _ := client.NewLogger(logLevel)
	c, err := client.NewClient(serverURL, nil, logger)
	if err != nil {
		return nil, err
	}

	// Apply version if specified
	version := viper.GetString("version")
	if version != "" {
		c = c.WithVersion(version)
	}

	token := viper.GetString("token")
	if token != "" {
		c = c.WithBearerToken(token)
	}

	return c, nil
}

func printOutput(data interface{}) error {
	switch output {
	case "json":
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	case "yaml":
		// TODO: Add YAML support if needed
		return fmt.Errorf("YAML output not yet implemented")
	case "table":
		// Simple table output
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	default:
		return fmt.Errorf("unknown output format: %s", output)
	}
}

var healthCmd = &cobra.Command{
	Use:   "health",
	Short: "Get service health status",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		health, err := c.GetHealth(ctx)
		if err != nil {
			return fmt.Errorf("failed to get health status: %w", err)
		}

		return printOutput(health)
	},
}

// setNestedField sets a field in a nested map using dot notation
// Example: setNestedField(map, "status.health", "OK") sets map["status"]["health"] = "OK"
func setNestedField(target map[string]interface{}, path string, value interface{}) {
	parts := strings.Split(path, ".")
	current := target

	// Navigate to the parent of the target field
	for _, part := range parts[:len(parts)-1] {
		if current[part] == nil {
			current[part] = make(map[string]interface{})
		}
		if nested, ok := current[part].(map[string]interface{}); ok {
			current = nested
		} else {
			// Convert to map if it's not already
			current[part] = make(map[string]interface{})
			current = current[part].(map[string]interface{})
		}
	}

	// Set the final field
	finalField := parts[len(parts)-1]
	if value == nil {
		// For unset operations, we use JSON Merge Patch null semantics
		current[finalField] = nil
	} else if stringValue, ok := value.(string); ok {
		// Try to parse as JSON first, then as string
		var jsonValue interface{}
		if err := json.Unmarshal([]byte(stringValue), &jsonValue); err == nil {
			current[finalField] = jsonValue
		} else {
			current[finalField] = stringValue
		}
	} else {
		current[finalField] = value
	}
}

// BootstrapTokenPolicy commands
var bootstraptokenpolicyCmd = &cobra.Command{
	Use:   "bootstraptokenpolicy",
	Short: "Manage bootstraptokenpolicys",
	Long:  `Create, read, update, patch, and delete bootstraptokenpolicys.`,
}

var bootstraptokenpolicyListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all bootstraptokenpolicys",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetBootstrapTokenPolicys(ctx)
		if err != nil {
			return fmt.Errorf("failed to list bootstraptokenpolicys: %w", err)
		}

		return printOutput(items)
	},
}

var bootstraptokenpolicyGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a BootstrapTokenPolicy by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetBootstrapTokenPolicy(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get BootstrapTokenPolicy: %w", err)
		}

		return printOutput(item)
	},
}

var bootstraptokenpolicyCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new BootstrapTokenPolicy",
	Long: `Create a new BootstrapTokenPolicy.

Examples:
  # Create from stdin
  echo '{"subject": "example-value", "audience": "example-value", "scopes": ["["item1","item2"]"], "ttl": 42, "refresh_ttl": 42, "TokenHash": "example-value", "expires_at": "{}", "binding_identifier": "example-value"}' | client bootstraptokenpolicy create

  # Create with --spec flag
  client bootstraptokenpolicy create --spec '{"subject": "example-value", "audience": "example-value", "scopes": ["["item1","item2"]"], "ttl": 42, "refresh_ttl": 42, "TokenHash": "example-value", "expires_at": "{}", "binding_identifier": "example-value"}'

Spec fields:
  subject (string) [required]
  audience (string) [required]
  scopes ([]string) [required]
  ttl (int64) [required]
  refresh_ttl (int64) [required]
  TokenHash (string)
  expires_at (time.Time) [required]
  binding_identifier (string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateBootstrapTokenPolicyRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateBootstrapTokenPolicy(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create BootstrapTokenPolicy: %w", err)
		}

		return printOutput(item)
	},
}

var bootstraptokenpolicyUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing BootstrapTokenPolicy",
	Long: `Update an existing BootstrapTokenPolicy.

Examples:
  # Update from stdin
  echo '{"subject": "example-value", "audience": "example-value", "scopes": ["["item1","item2"]"], "ttl": 42, "refresh_ttl": 42, "TokenHash": "example-value", "expires_at": "{}", "binding_identifier": "example-value"}' | client bootstraptokenpolicy update <uid>

  # Update with --spec flag
  client bootstraptokenpolicy update <uid> --spec '{"subject": "example-value", "audience": "example-value", "scopes": ["["item1","item2"]"], "ttl": 42, "refresh_ttl": 42, "TokenHash": "example-value", "expires_at": "{}", "binding_identifier": "example-value"}'

Spec fields:
  subject (string) [required]
  audience (string) [required]
  scopes ([]string) [required]
  ttl (int64) [required]
  refresh_ttl (int64) [required]
  TokenHash (string)
  expires_at (time.Time) [required]
  binding_identifier (string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateBootstrapTokenPolicyRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateBootstrapTokenPolicy(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update BootstrapTokenPolicy: %w", err)
		}

		return printOutput(item)
	},
}

var bootstraptokenpolicyPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a BootstrapTokenPolicy",
	Long: `Patch an existing BootstrapTokenPolicy spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client bootstraptokenpolicy patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client bootstraptokenpolicy patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client bootstraptokenpolicy patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client bootstraptokenpolicy patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchBootstrapTokenPolicy(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch BootstrapTokenPolicy: %w", err)
		}

		return printOutput(item)
	},
}

var bootstraptokenpolicyDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a BootstrapTokenPolicy",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteBootstrapTokenPolicy(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete BootstrapTokenPolicy: %w", err)
		}

		fmt.Printf("BootstrapTokenPolicy %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	bootstraptokenpolicyCmd.AddCommand(bootstraptokenpolicyListCmd)
	bootstraptokenpolicyCmd.AddCommand(bootstraptokenpolicyGetCmd)
	bootstraptokenpolicyCmd.AddCommand(bootstraptokenpolicyCreateCmd)
	bootstraptokenpolicyCmd.AddCommand(bootstraptokenpolicyUpdateCmd)
	bootstraptokenpolicyCmd.AddCommand(bootstraptokenpolicyPatchCmd)
	bootstraptokenpolicyCmd.AddCommand(bootstraptokenpolicyDeleteCmd)

	// Add spec flag for create and update commands
	bootstraptokenpolicyCreateCmd.Flags().String("spec", "", "BootstrapTokenPolicy specification in JSON format")
	bootstraptokenpolicyUpdateCmd.Flags().String("spec", "", "BootstrapTokenPolicy specification in JSON format")

	// Add patch command flags
	bootstraptokenpolicyPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	bootstraptokenpolicyPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	bootstraptokenpolicyPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	bootstraptokenpolicyPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	bootstraptokenpolicyPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	bootstraptokenpolicyPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// RefreshTokenFamily commands
var refreshtokenfamilyCmd = &cobra.Command{
	Use:   "refreshtokenfamily",
	Short: "Manage refreshtokenfamilys",
	Long:  `Create, read, update, patch, and delete refreshtokenfamilys.`,
}

var refreshtokenfamilyListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all refreshtokenfamilys",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetRefreshTokenFamilys(ctx)
		if err != nil {
			return fmt.Errorf("failed to list refreshtokenfamilys: %w", err)
		}

		return printOutput(items)
	},
}

var refreshtokenfamilyGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a RefreshTokenFamily by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetRefreshTokenFamily(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get RefreshTokenFamily: %w", err)
		}

		return printOutput(item)
	},
}

var refreshtokenfamilyCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new RefreshTokenFamily",
	Long: `Create a new RefreshTokenFamily.

Examples:
  # Create from stdin
  echo '{"family_id": "example-value", "CurrentTokenHash": "example-value", "subject": "example-value", "audience": "example-value", "scopes": ["["item1","item2"]"], "issued_at": "{}", "expires_at": "{}", "binding_identifier": "example-value"}' | client refreshtokenfamily create

  # Create with --spec flag
  client refreshtokenfamily create --spec '{"family_id": "example-value", "CurrentTokenHash": "example-value", "subject": "example-value", "audience": "example-value", "scopes": ["["item1","item2"]"], "issued_at": "{}", "expires_at": "{}", "binding_identifier": "example-value"}'

Spec fields:
  family_id (string) [required]
  CurrentTokenHash (string)
  subject (string) [required]
  audience (string) [required]
  scopes ([]string) [required]
  issued_at (time.Time) [required]
  expires_at (time.Time) [required]
  binding_identifier (string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateRefreshTokenFamilyRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateRefreshTokenFamily(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create RefreshTokenFamily: %w", err)
		}

		return printOutput(item)
	},
}

var refreshtokenfamilyUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing RefreshTokenFamily",
	Long: `Update an existing RefreshTokenFamily.

Examples:
  # Update from stdin
  echo '{"family_id": "example-value", "CurrentTokenHash": "example-value", "subject": "example-value", "audience": "example-value", "scopes": ["["item1","item2"]"], "issued_at": "{}", "expires_at": "{}", "binding_identifier": "example-value"}' | client refreshtokenfamily update <uid>

  # Update with --spec flag
  client refreshtokenfamily update <uid> --spec '{"family_id": "example-value", "CurrentTokenHash": "example-value", "subject": "example-value", "audience": "example-value", "scopes": ["["item1","item2"]"], "issued_at": "{}", "expires_at": "{}", "binding_identifier": "example-value"}'

Spec fields:
  family_id (string) [required]
  CurrentTokenHash (string)
  subject (string) [required]
  audience (string) [required]
  scopes ([]string) [required]
  issued_at (time.Time) [required]
  expires_at (time.Time) [required]
  binding_identifier (string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateRefreshTokenFamilyRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateRefreshTokenFamily(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update RefreshTokenFamily: %w", err)
		}

		return printOutput(item)
	},
}

var refreshtokenfamilyPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a RefreshTokenFamily",
	Long: `Patch an existing RefreshTokenFamily spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client refreshtokenfamily patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client refreshtokenfamily patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client refreshtokenfamily patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client refreshtokenfamily patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchRefreshTokenFamily(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch RefreshTokenFamily: %w", err)
		}

		return printOutput(item)
	},
}

var refreshtokenfamilyDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a RefreshTokenFamily",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteRefreshTokenFamily(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete RefreshTokenFamily: %w", err)
		}

		fmt.Printf("RefreshTokenFamily %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	refreshtokenfamilyCmd.AddCommand(refreshtokenfamilyListCmd)
	refreshtokenfamilyCmd.AddCommand(refreshtokenfamilyGetCmd)
	refreshtokenfamilyCmd.AddCommand(refreshtokenfamilyCreateCmd)
	refreshtokenfamilyCmd.AddCommand(refreshtokenfamilyUpdateCmd)
	refreshtokenfamilyCmd.AddCommand(refreshtokenfamilyPatchCmd)
	refreshtokenfamilyCmd.AddCommand(refreshtokenfamilyDeleteCmd)

	// Add spec flag for create and update commands
	refreshtokenfamilyCreateCmd.Flags().String("spec", "", "RefreshTokenFamily specification in JSON format")
	refreshtokenfamilyUpdateCmd.Flags().String("spec", "", "RefreshTokenFamily specification in JSON format")

	// Add patch command flags
	refreshtokenfamilyPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	refreshtokenfamilyPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	refreshtokenfamilyPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	refreshtokenfamilyPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	refreshtokenfamilyPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	refreshtokenfamilyPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// TokenHierarchy commands
var tokenhierarchyCmd = &cobra.Command{
	Use:   "tokenhierarchy",
	Short: "Manage tokenhierarchys",
	Long:  `Create, read, update, patch, and delete tokenhierarchys.`,
}

var tokenhierarchyListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all tokenhierarchys",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetTokenHierarchys(ctx)
		if err != nil {
			return fmt.Errorf("failed to list tokenhierarchys: %w", err)
		}

		return printOutput(items)
	},
}

var tokenhierarchyGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a TokenHierarchy by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetTokenHierarchy(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get TokenHierarchy: %w", err)
		}

		return printOutput(item)
	},
}

var tokenhierarchyCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new TokenHierarchy",
	Long: `Create a new TokenHierarchy.

Examples:
  # Create from stdin
  echo '{"parent_token_id": "example-value", "child_token_id": "example-value", "subject": "example-value", "inherited_claims": "{}", "created_at": "{}", "depth": 42}' | client tokenhierarchy create

  # Create with --spec flag
  client tokenhierarchy create --spec '{"parent_token_id": "example-value", "child_token_id": "example-value", "subject": "example-value", "inherited_claims": "{}", "created_at": "{}", "depth": 42}'

Spec fields:
  parent_token_id (string) [required]
  child_token_id (string) [required]
  subject (string) [required]
  inherited_claims (v1.InheritedClaims) [required]
  created_at (time.Time) [required]
  depth (int)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateTokenHierarchyRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateTokenHierarchy(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create TokenHierarchy: %w", err)
		}

		return printOutput(item)
	},
}

var tokenhierarchyUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing TokenHierarchy",
	Long: `Update an existing TokenHierarchy.

Examples:
  # Update from stdin
  echo '{"parent_token_id": "example-value", "child_token_id": "example-value", "subject": "example-value", "inherited_claims": "{}", "created_at": "{}", "depth": 42}' | client tokenhierarchy update <uid>

  # Update with --spec flag
  client tokenhierarchy update <uid> --spec '{"parent_token_id": "example-value", "child_token_id": "example-value", "subject": "example-value", "inherited_claims": "{}", "created_at": "{}", "depth": 42}'

Spec fields:
  parent_token_id (string) [required]
  child_token_id (string) [required]
  subject (string) [required]
  inherited_claims (v1.InheritedClaims) [required]
  created_at (time.Time) [required]
  depth (int)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateTokenHierarchyRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateTokenHierarchy(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update TokenHierarchy: %w", err)
		}

		return printOutput(item)
	},
}

var tokenhierarchyPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a TokenHierarchy",
	Long: `Patch an existing TokenHierarchy spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client tokenhierarchy patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client tokenhierarchy patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client tokenhierarchy patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client tokenhierarchy patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchTokenHierarchy(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch TokenHierarchy: %w", err)
		}

		return printOutput(item)
	},
}

var tokenhierarchyDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a TokenHierarchy",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteTokenHierarchy(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete TokenHierarchy: %w", err)
		}

		fmt.Printf("TokenHierarchy %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	tokenhierarchyCmd.AddCommand(tokenhierarchyListCmd)
	tokenhierarchyCmd.AddCommand(tokenhierarchyGetCmd)
	tokenhierarchyCmd.AddCommand(tokenhierarchyCreateCmd)
	tokenhierarchyCmd.AddCommand(tokenhierarchyUpdateCmd)
	tokenhierarchyCmd.AddCommand(tokenhierarchyPatchCmd)
	tokenhierarchyCmd.AddCommand(tokenhierarchyDeleteCmd)

	// Add spec flag for create and update commands
	tokenhierarchyCreateCmd.Flags().String("spec", "", "TokenHierarchy specification in JSON format")
	tokenhierarchyUpdateCmd.Flags().String("spec", "", "TokenHierarchy specification in JSON format")

	// Add patch command flags
	tokenhierarchyPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	tokenhierarchyPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	tokenhierarchyPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	tokenhierarchyPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	tokenhierarchyPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	tokenhierarchyPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}
