# Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
#
# SPDX-License-Identifier: MIT

name: OpenSSF Scorecard

on:
  # Scan on pushes to default branch
  push:
    branches: [ main, master ]
  # Nightly (UTC) checks so the badge stays fresh
  schedule:
    - cron: '0 3 * * *'
  # Run when branch protection changes (recommended by OSSF)
  branch_protection_rule:
  # Manual trigger
  workflow_dispatch:

# Minimal permissions at the workflow level
permissions: read-all

jobs:
  scorecard:
    runs-on: ubuntu-latest
    # Fine-grained permissions for this job
    permissions:
      contents: read           # to read the repo
      actions: read            # to detect CI usage
      id-token: write          # to publish results to the OpenSSF DB (OIDC)
      security-events: write   # to upload SARIF to the Security tab

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 0 = full history; some checks (like Branch-Protection) benefit from this
          fetch-depth: 0

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          # Output SARIF so we can surface findings in the Security tab
          results_file: results.sarif
          results_format: sarif
          # Publish to the public Scorecard DB so your badge works
          publish_results: true
          # GITHUB_TOKEN is enough for repo metadata
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      # Upload SARIF to GitHub code scanning (Security tab)
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      # Keep a copy of the raw results as a build artifact
      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@v4
        with:
          name: openssf-scorecard-results
          path: results.sarif
          retention-days: 7
